### ISSUE TITLE
Incorrect national flag emoji for Traditional Chinese language

### ISSUE THREAD

**Issue by pinchih** [mohakapt/Stringz#17]
Incorrect national flag emoji for traditional Chinese language.

__Version:__
0.6.4 (41)

__Steps to reproduce:__
From the language dropdown button, select **Chinese (Traditional)** -> At the first row, the national flag emoji is showing China's national flag.

__Screenshot:__
![Screen Shot 2021-03-19 at 6 05 54 PM](https://user-images.githubusercontent.com/12094516/111847345-00f3e300-88df-11eb-8d6f-b92dfd2ac95e.png)

__Suggestion to fix this issue:__
Change the national flag emoji from 🇨🇳(China) to 🇹🇼(Taiwan).

Thank you very much!

**Comment by mohakapt** [comment]
I didn't know that Traditional Chinese is mostly used in Taiwan, I updated the flag and will publish it with the next version as soon as possible.
Thanks for reporting.
