### ISSUE TITLE
The space between value and semicolon makes whole line cannot be recognized.

### ISSUE THREAD

**Issue by vulgur** [mohakapt/Stringz#18]
Some localizations are marked as unlocalized because of such situation.
<img width="337" alt="image" src="https://user-images.githubusercontent.com/3339536/112780912-66349a80-907c-11eb-88ce-0c9f8f788d16.png">

**Comment by mohakapt** [comment]
Thanks for reporting the issue, This issue is now fixed in v0.7.0.
