### ISSUE TITLE
Some localization items are deleted

### ISSUE THREAD

**Issue by vulgur** [mohakapt/Stringz#19]
This app would delete items like below, “restore" was been deleted after editing by the app.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/3339536/112782567-ead4e800-907f-11eb-8d0e-c67f24e77282.png">

**Comment by mohakapt** [comment]
That's weird 🤔, is the string being deleted because it's name is "restore"? or is it happening for other strings?

**Comment by vulgur** [comment]
Yes, it happens for other strings. All such strings has a comment line(//xxxxx) before them.
