### ISSUE TITLE
Crash on attempting to open Xcode project

### ISSUE THREAD

**Issue by massimobio** [mohakapt/Stringz#3]
My project is part of a workspace if that's of any importance.
macOS 10.15.7
Xcode 12.3
Here's the crash report:

[stacktrace.txt](https://github.com/mohakapt/Stringz/files/5736389/stacktrace.txt)

**Comment by massimobio** [comment]
Still crashes in 0.3.2:

[stringz 032 crash.txt](https://github.com/mohakapt/Stringz/files/5736475/stringz.032.crash.txt)

**Comment by mohakapt** [comment]
I don't think it has something to do with the project being in a workspace, I'm testing the application on a lot of open source projects like [Wikipedia iOS](https://github.com/wikimedia/wikipedia-ios) and [DuckDuckGo](https://github.com/duckduckgo/iOS) and so far it seems to load localization files correctly. Anyways I'm still investigating your crash, Thanks for submitting a stacktrace.

**Comment by mohakapt** [comment]
Just a question is it crashing as soon as you load your project or after selecting an item in the sidebar?

**Comment by massimobio** [comment]
It crashes as soon as click on Open on the initial menu.

**Comment by massimobio** [comment]
I did some more tests and I cannot open any project.
Besides my own projects I unsuccessfully tried these open source ones: [SVProgressHUD](https://github.com/SVProgressHUD/SVProgressHUD) and [SwiftStoreKit](https://github.com/bizz84/SwiftyStoreKit)

**Comment by mohakapt** [comment]
I'm testing on these projects right now, meanwhile could you please try to open the [SampleApp](https://github.com/mohakapt/Stringz/tree/master/SampleApp) from this repository in Stringz on your machine.

**Comment by massimobio** [comment]
Crashes as well. Maybe some sandboxing issue, or file access permission, or some difference between the debug version and the release version of the app?

**Comment by mohakapt** [comment]
Not sure about sandboxing but I tested the app both in debug and release and it seems to load correctly even on the projects you sent. I noticed you're running on 10.15.7 and I'm testing and developing on 11.1, Right now I'm downloading macOS Catalina to test the app on.

**Comment by mohakapt** [comment]
I think i figured it out, I downloaded macOS Catalina, ran the app on and fixed all the issues a found (most of them are related to me using a new framework). Please have try version 0.4.0 and see if it works.

**Comment by massimobio** [comment]
Yes! It works now, thank you.
