### ISSUE TITLE
Support for More Languages

### ISSUE THREAD

**Issue by Sherlouk** [mohakapt/Stringz#32]
Welsh is jumping to mind for me and my app personally, but Xcode supports hundreds more languages than Stringz currently shows 👀 

🏴󠁧󠁢󠁷󠁬󠁳󠁿

**Comment by samuelbradshaw** [comment]
I added several languages a few months ago, but I didn't include Welsh. It would need to be added here (in three places, `Language`, `friendlyName`, and `flag`):
https://github.com/mohakapt/Stringz/blob/main/Stringz/Language.swift
