### ISSUE TITLE
Bring it to windows .

### ISSUE THREAD

**Issue by DogancanYr** [mohakapt/Stringz#39]
Bring it to windows .

**Comment by yamankatby** [comment]
Hey @DogancanYr,

Thank you for raising this issue, however, I wonder how it can be useful on windows.

**Comment by DogancanYr** [comment]
There is no such thing as everyone will use macos.

**Comment by yamankatby** [comment]
Hey @DogancanYr,

Thank you for your response, this app aims to help developers to localize their Xcode (iOS, macOS, tvOS, and watchOS) apps which can be developed only on macOS.

Closing as not-planned, feel free to reopen if you think it is not resolved yet.
